
CREATE TABLE [dbo].[events_adult_needs_assessments](
	[person_id] [numeric](16, 0) NULL,
	[root_step_id] [numeric](9, 0) NULL,
	[workflow_step_id] [numeric](9, 0) NULL,
	[workflow_step_type] [varchar](100) NULL,
	[status] [varchar](16) NULL,
	[proposed_date] [datetime] NULL,
	[assigned_team] [varchar](240) NULL,
	[assigned_worker] [varchar](61) NULL,
	[assigned_team_id] [numeric](9, 0) NULL,
	[assigned_worker_id] [numeric](9, 0) NULL,
	[working_days_between_proposed_and_completed] [int] NULL,
	[pi_within_28_working_days] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[events_all]    Script Date: 11/04/2023 13:25:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[events_all](
	[root_step_id] [numeric](9, 0) NULL,
	[workflow_step_id] [numeric](9, 0) NULL,
	[workflow_step_type] [varchar](100) NULL,
	[person_id] [numeric](16, 0) NULL,
	[depth] [numeric](4, 0) NULL,
	[template_id] [int] NULL,
	[proposed_date] [datetime] NULL,
	[incoming_date] [datetime] NULL,
	[started_date] [datetime] NULL,
	[completed_date] [datetime] NULL,
	[cancelled_date] [datetime] NULL,
	[status] [varchar](16) NULL,
	[assigned_team] [varchar](240) NULL,
	[assigned_worker] [varchar](61) NULL,
	[assigned_team_id] [numeric](9, 0) NULL,
	[assigned_worker_id] [numeric](9, 0) NULL,
	[root_started_date] [datetime] NULL,
	[root_proposed_date] [datetime] NULL,
	[days_proposed_to_started] [int] NULL,
	[days_started_to_completed] [int] NULL,
	[days_proposed_to_completed] [int] NULL,
	[days_root_started_to_current_completed] [int] NULL,
	[days_root_proposed_to_current_completed] [int] NULL,
	[working_days_proposed_to_started] [int] NULL,
	[working_days_started_to_completed] [int] NULL,
	[working_days_proposed_to_completed] [int] NULL,
	[working_days_root_started_to_current_completed] [int] NULL,
	[working_days_root_proposed_to_current_completed] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[form_needs_assessments]    Script Date: 11/04/2023 13:25:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[form_needs_assessments](
	[workflow_step_id] [numeric](9, 0) NULL,
	[form_id] [numeric](9, 0) NULL,
	[person_id] [numeric](16, 0) NULL,
	[created_on] [datetime] NULL,
	[finished_on] [datetime] NULL,
	[template_id] [numeric](9, 0) NULL,
	[template_version_id] [numeric](9, 0) NULL,
	[workflow_activity_type_id] [numeric](9, 0) NULL,
	[workflow_activity_order] [numeric](9, 0) NULL,
	[form_batch_schedule_id] [numeric](9, 0) NULL,
	[created_by_worker_id] [numeric](9, 0) NULL,
	[created_for_worker_id] [numeric](9, 0) NULL,
	[clientName] [varchar](4000) NULL,
	[clientEthnicity] [varchar](4000) NULL,
	[clientSubEthnicity] [varchar](4000) NULL,
	[clientNHSNumber] [varchar](4000) NULL,
	[SUG] [varchar](4000) NULL,
	[clientPSRSubCategory] [varchar](4000) NULL,
	[gpName] [varchar](4000) NULL,
	[gpTelephone] [varchar](4000) NULL,
	[e4d1ea30 - 671e - 46b5 - ad0b - ae2081c0a2ba] [varchar](4000) NULL,
	[imcaName] [varchar](4000) NULL,
	[imcaHiddenField] [varchar](4000) NULL,
	[bestInterestsAssessmentDecisionMaker] [varchar](4000) NULL,
	[f0a69b1f - f95e - 49c0 - 9c49 - af02447c74b3] [varchar](4000) NULL,
	[mainCarerName] [varchar](4000) NULL,
	[mainCarerRelationship] [varchar](4000) NULL,
	[carerID] [varchar](4000) NULL,
	[familyCareSomeoneElseHidden] [varchar](4000) NULL,
	[familyCareProvidedInformalCarerHidden] [varchar](4000) NULL,
	[communicationHidden] [varchar](4000) NULL,
	[capacityDecisionsHidden] [varchar](4000) NULL,
	[personalCareDayHidden] [varchar](4000) NULL,
	[personalCareNightHidden] [varchar](4000) NULL,
	[eatingDrinkingHidden] [varchar](4000) NULL,
	[runningHomeHidden] [varchar](4000) NULL,
	[healthWellbeingHidden] [varchar](4000) NULL,
	[healthStabilityHidden] [varchar](4000) NULL,
	[communityParticipationHidden] [varchar](4000) NULL,
	[communityAccessHidden] [varchar](4000) NULL,
	[communityTravelHidden] [varchar](4000) NULL,
	[livingSafelyHidden] [varchar](4000) NULL,
	[riskBehaviourHidden] [varchar](4000) NULL,
	[countUnableToAchieve] [varchar](4000) NULL,
	[countAbleToAchieve] [varchar](4000) NULL,
	[jobTitleAssessor] [varchar](4000) NULL,
	[team] [varchar](4000) NULL,
	[hiddenFieldJointAssessor] [varchar](4000) NULL,
	[tickRecordKeyTeam] [varchar](4000) NULL,
	[hiddenFieldKeyTeam] [varchar](4000) NULL,
	[accommodationTenureType] [varchar](4000) NULL,
	[completionDateConditionalMandatoryFieldHidden] [varchar](4000) NULL,
	[assessmentCompletedCancelledDateHidden] [varchar](4000) NULL,
	[assessmentCompletedBy] [varchar](4000) NULL,
	[assessmentCompletedByValidationHidden] [varchar](4000) NULL,
	[mainCarerDetails] [varchar](4000) NULL,
	[imcaOrganisation] [varchar](4000) NULL,
	[hiddenNotice] [varchar](4000) NULL,
	[checkedBy] [varchar](4000) NULL,
	[nameGP] [varchar](4000) NULL,
	[idSurgeryGP] [varchar](4000) NULL,
	[telephoneGP] [varchar](4000) NULL,
	[nameGPSurgery] [varchar](4000) NULL,
	[idGPSurgery] [varchar](4000) NULL,
	[telephoneGPSurgery] [varchar](4000) NULL,
	[hiddenGPMandatory] [varchar](4000) NULL,
	[hiddenConfirmationGPSurgery] [varchar](4000) NULL,
	[confirmationGPSurgery] [varchar](4000) NULL,
	[hiddenUpdateGPSurgery] [varchar](4000) NULL,
	[hiddenOrganisationIDMatch] [varchar](4000) NULL,
	[assessmentCompletedByTeamHidden] [varchar](4000) NULL,
	[choiceSurveyConfirm] [varchar](4000) NULL,
	[validateChoiceSurveyConfirm] [varchar](4000) NULL,
	[choiceSurveyConfirmation] [varchar](4000) NULL,
	[choiceSurveyConfirmationHidden] [varchar](4000) NULL,
	[confirmAdvisedInvolvedPrivacy] [varchar](4000) NULL,
	[confirmAdvisedInvolvedPrivacyValidationHidden] [varchar](4000) NULL,
	[petContingencyPlanConfirmation] [varchar](4000) NULL,
	[petContingencyPlanConfirmationHidden] [varchar](4000) NULL,
	[reasonNoTechnologyConversationHidden] [varchar](4000) NULL,
	[technologyCurrentlyUsedHidden] [varchar](4000) NULL,
	[technologyUsageHidden] [varchar](4000) NULL,
	[barriersUsingTechnologyHidden] [varchar](4000) NULL,
	[undecidedUseTechnologyHidden] [varchar](4000) NULL,
	[clientDOB] [datetime] NULL,
	[mainCarerDOB] [datetime] NULL,
	[lastAnnualHealthCheck] [datetime] NULL,
	[completionDate] [datetime] NULL,
	[assessmentCancelledDate] [datetime] NULL,
	[accommodationResidentLincolnshire] [varchar](4000) NULL,
	[capacityConsentAssessment] [varchar](4000) NULL,
	[consentAssessment] [varchar](4000) NULL,
	[copyLCCPrivacyStatement] [varchar](4000) NULL,
	[appointedActOnPersonsBehalf] [varchar](4000) NULL,
	[imcaInvolved] [varchar](4000) NULL,
	[bestInterestsAssessment] [varchar](4000) NULL,
	[careSupportNeeds1] [varchar](4000) NULL,
	[liveWithAnyone] [varchar](4000) NULL,
	[actAsCarer] [varchar](4000) NULL,
	[youngPersonInvolvedImpacted] [varchar](4000) NULL,
	[youngPersonActingAsCarer] [varchar](4000) NULL,
	[youngPersonConcernsSafety] [varchar](4000) NULL,
	[carersAssessment] [varchar](4000) NULL,
	[referredCarersService] [varchar](4000) NULL,
	[careSupportNeeds2] [varchar](4000) NULL,
	[careSupportNeeds3] [varchar](4000) NULL,
	[careSupportNeeds4] [varchar](4000) NULL,
	[careSupportNeeds5] [varchar](4000) NULL,
	[careSupportNeeds6] [varchar](4000) NULL,
	[careSupportNeeds7] [varchar](4000) NULL,
	[careSupportNeeds8] [varchar](4000) NULL,
	[prisma7FrailtyChecklist] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion1] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion2] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion3] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion4] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion5] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion6] [varchar](4000) NULL,
	[prisma7FrailtyChecklistQuestion7] [varchar](4000) NULL,
	[healthActionPlan] [varchar](4000) NULL,
	[chcCompleted] [varchar](4000) NULL,
	[chcMonitoringStepUnderway] [varchar](4000) NULL,
	[careSupportNeeds9] [varchar](4000) NULL,
	[furtherRAMPRequired] [varchar](4000) NULL,
	[safeguardingConcerns] [varchar](4000) NULL,
	[rasRequired] [varchar](4000) NULL,
	[eligibilityDeterminationNeeds] [varchar](4000) NULL,
	[outcome1] [varchar](4000) NULL,
	[outcome2] [varchar](4000) NULL,
	[outcome3] [varchar](4000) NULL,
	[outcome4] [varchar](4000) NULL,
	[outcome5] [varchar](4000) NULL,
	[outcome6] [varchar](4000) NULL,
	[outcome7] [varchar](4000) NULL,
	[outcome8] [varchar](4000) NULL,
	[outcome9] [varchar](4000) NULL,
	[outcome10] [varchar](4000) NULL,
	[ableToAchieve1] [varchar](4000) NULL,
	[ableToAchieve2] [varchar](4000) NULL,
	[ableToAchieve3] [varchar](4000) NULL,
	[ableToAchieve4] [varchar](4000) NULL,
	[ableToAchieve5] [varchar](4000) NULL,
	[ableToAchieve6] [varchar](4000) NULL,
	[ableToAchieve7] [varchar](4000) NULL,
	[ableToAchieve8] [varchar](4000) NULL,
	[ableToAchieve9] [varchar](4000) NULL,
	[ableToAchieve10] [varchar](4000) NULL,
	[significantImpactWellbeing] [varchar](4000) NULL,
	[eligibleForService] [varchar](4000) NULL,
	[eligibility1] [varchar](4000) NULL,
	[eligibility2] [varchar](4000) NULL,
	[eligibility3] [varchar](4000) NULL,
	[eligibility4] [varchar](4000) NULL,
	[eligibility5] [varchar](4000) NULL,
	[eligibility6] [varchar](4000) NULL,
	[eligibility7] [varchar](4000) NULL,
	[eligibility8] [varchar](4000) NULL,
	[eligibility9] [varchar](4000) NULL,
	[eligibility10] [varchar](4000) NULL,
	[careSupportPlanRequired] [varchar](4000) NULL,
	[advisedContributionCostSupport] [varchar](4000) NULL,
	[howAssessmentConducted] [varchar](4000) NULL,
	[documentInfoDropdown] [varchar](4000) NULL,
	[assessmentAreaTeam] [varchar](4000) NULL,
	[supportedSelfAssessment] [varchar](4000) NULL,
	[jointAssessment] [varchar](4000) NULL,
	[assessmentCancelled] [varchar](4000) NULL,
	[assessmentCancelledReason] [varchar](4000) NULL,
	[actAsCarerForSomeoneElse] [varchar](4000) NULL,
	[informalNeeds] [varchar](4000) NULL,
	[otherCarersIdentified] [varchar](4000) NULL,
	[actAsCarerForSomeoneElseReferredCarersService] [varchar](4000) NULL,
	[actAsCarerForSomeoneElseInformalNeeds] [varchar](4000) NULL,
	[actAsCarerForSomeoneElseCarersAssessment] [varchar](4000) NULL,
	[s117Eligible] [varchar](4000) NULL,
	[s117Verification] [varchar](4000) NULL,
	[hiddenCarersAssessment] [varchar](4000) NULL,
	[cerpConsidered] [varchar](4000) NULL,
	[planUpToDate] [varchar](4000) NULL,
	[cerpOffered] [varchar](4000) NULL,
	[actAsCarerForSomeoneElseCERPConsidered] [varchar](4000) NULL,
	[actAsCarerForSomeoneElseplanUpToDate] [varchar](4000) NULL,
	[actAsCarerForSomeoneElseCERPOffered] [varchar](4000) NULL,
	[choiceSurvey] [varchar](4000) NULL,
	[contributedCompletionAssessment] [varchar](4000) NULL,
	[changesAffectRisksIdentified] [varchar](4000) NULL,
	[petOwnership] [varchar](4000) NULL,
	[technologyConversation] [varchar](4000) NULL,
	[technologyConversationCurrentlyUsed] [varchar](4000) NULL,
	[technologyConversationAdditionalUsage] [varchar](4000) NULL,
	[technologyConversationUsage] [varchar](4000) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[km_conversations_to_assessments]    Script Date: 11/04/2023 13:25:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[km_conversations_to_assessments](
	[root_step_id] [numeric](9, 0) NULL,
	[conversation_step_id] [numeric](9, 0) NULL,
	[conversation_type] [varchar](100) NULL,
	[person_id] [numeric](16, 0) NULL,
	[conversation_status] [varchar](16) NULL,
	[proposed_date] [datetime] NULL,
	[conversation_completed_date] [datetime] NULL,
	[assessment_started_date] [datetime] NULL,
	[assessment_status] [varchar](16) NULL,
	[assessment_type] [varchar](100) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[people]    Script Date: 11/04/2023 13:25:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[people](
	[PERSON_ID] [numeric](16, 0) NULL,
	[SSDA903_ID] [varchar](10) NULL,
	[NHS_ID] [numeric](10, 0) NULL,
	[SCN_ID] [numeric](9, 0) NULL,
	[UPN_ID] [varchar](13) NULL,
	[FORMER_UPN_ID] [varchar](13) NULL,
	[FULL_NAME] [varchar](62) NULL,
	[TITLE] [varchar](8) NULL,
	[FIRST_NAME] [varchar](30) NULL,
	[LAST_NAME] [varchar](30) NULL,
	[DATE_OF_BIRTH] [datetime] NULL,
	[DATE_OF_DEATH] [datetime] NULL,
	[GENDER] [varchar](1) NULL,
	[RESTRICTED] [varchar](1) NULL,
	[PERSON_ID_LEGACY] [varchar](16) NULL,
	[FULL_ETHNICITY_CODE] [varchar](33) NULL,
	[COUNTRY_OF_BIRTH_CODE] [varchar](16) NULL,
	[IS_CHILD_LEGACY] [varchar](1) NULL,
	[IS_ADULT_LEGACY] [varchar](1) NULL,
	[NATIONALITY] [varchar](80) NULL,
	[RELIGION] [varchar](80) NULL,
	[MARITAL_STATUS] [varchar](80) NULL,
	[FIRST_LANGUAGE] [varchar](100) NULL,
	[FLUENCY_IN_ENGLISH] [varchar](100) NULL,
	[EMAIL_ADDRESS] [varchar](240) NULL,
	[CONTEXT_FLAG] [varchar](1) NULL,
	[SCRA_ID] [varchar](13) NULL,
	[INTERPRETER_REQUIRED] [varchar](1) NULL,
	[IDENTIFIED_GENDER] [varchar](80) NULL,
	[Age_Decimal] [numeric](17, 6) NULL,
	[Age] [numeric](17, 6) NULL,
	[Redacted_First_Name] [nvarchar](30) NULL,
	[Redacted_Last_Name] [nvarchar](30) NULL,
	[Redacted_DOB] [datetime] NULL,
	[Redacted_Gender] [nvarchar](5) NULL,
	[Unborn] [int] NULL,
	[Unborn_Under18] [int] NULL,
	[ID] [numeric](9, 0) NULL,
	[ADDRESS] [varchar](509) NULL,
	[ADDRESS_LINE_1] [varchar](245) NULL,
	[ADDRESS_LINE_2] [varchar](100) NULL,
	[ADDRESS_LINE_3] [varchar](80) NULL,
	[ADDRESS_LINE_4] [varchar](80) NULL,
	[POST_CODE] [varchar](16) NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[DISPLAY_ADDRESS] [varchar](1) NULL,
	[IS_PRIMARY] [varchar](1) NULL,
	[ETHNICITY] [varchar](80) NULL,
	[Easting] [varchar](15) NULL,
	[Northing] [varchar](15) NULL,
	[Positional Quality] [varchar](15) NULL,
	[County Code] [varchar](500) NULL,
	[County Name] [varchar](500) NULL,
	[Local Authority Code] [varchar](500) NULL,
	[Local Authority Name] [varchar](500) NULL,
	[District_Code] [varchar](500) NULL,
	[District_Name] [varchar](500) NULL,
	[Country Code] [varchar](500) NULL,
	[Region Code] [varchar](500) NULL,
	[Region Name] [varchar](500) NULL,
	[Parliamentary Constituency Code] [varchar](500) NULL,
	[Parliamentary Constituency Name] [varchar](500) NULL,
	[European Electoral Region Code] [varchar](500) NULL,
	[European Electoral Region Name] [varchar](500) NULL,
	[Primary Care Trust Code] [varchar](500) NULL,
	[Primary Care Trust Name] [varchar](500) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [LPFT] SET  READ_WRITE 
GO
